spring:
  h2:
    console:
      enabled: false
  data:
    redis:
      host: ${REDIS_HOST:redis}
      port: ${REDIS_PORT:6379}

app:
  cors:
    allowed-origins:
      - http://localhost:3000
      - http://127.0.0.1:3000
